import { builtinModules } from "node:module";
import esbuild from "esbuild";
import fs from "fs";
import path from "path";
import process from "process";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const outdir = prod ? "dist" : "dev-vault";

//- **Warning**: Build verification failed: the `build` script exited with an error.
// - Ensure `npm/pnpm/yarn/bun run build` completes successfully in a clean environment.
if (prod)
    fs.mkdirSync(outdir, { recursive: true });

fs.copyFileSync("manifest.json", path.join(outdir, "manifest.json"));

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	// When you use an object for entryPoints, the keys become the output filenames and the values are the input file paths.
	entryPoints: {
		main: "src/main.ts",
		styles: "styles/main.css"
	},
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	// Runtime of min supported Obsidian version 1.8.2, see manifest.json
	// Adding "safari15" ensures CSS nesting is flattened during minify for compatibility with older iOS/WebKit versions (ios 15); i.e., if it is removed, the resulting css file will preserve any nested selectors, which is not supported in WebKit until iOS 17.2.
	target: ["es2022", "safari15"],
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outdir: outdir,
	minify: prod,
	define: {
		"process.env.NODE_ENV": prod ? '"production"' : '"development"',
	},
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
